### ISSUE TITLE
Failed builds because of missing database extensions

### ISSUE THREAD

**Issue by dreispt** [sbidoul/runboat#32]
Error found in [this](https://runboat.odoo-community.org/api/v1/builds/bc79feda4-d59e-4d71-887a-e13d77d7bddd/init-log) build:
```
2021-12-06 11:27:39,646 526 WARNING bc79feda4-d59e-4d71-887a-e13d77d7bddd odoo.addons.base_search_fuzzy.models.trgm_index: To use pg_trgm you have to create the extension pg_trgm in your database or you have to be the superuser. 
```

**Comment by sbidoul** [comment]
I have installed `pg_trgm` on the `template1` database so this should now be resolved.

There is currently no way to reinitialize a build (tracked in #34), so you need to push a commit.

**Comment by sbidoul** [comment]
Note unaccent and postgis are also preinstalled.

**Comment by sbidoul** [comment]
Update: since Odoo is using template0 by default, I had to implement #35 for this to be effective. This is now deployed.
