### ISSUE TITLE
[rsync] Install fail due to apt package change

### ISSUE THREAD

**Issue by rousseldenis** [sbidoul/runboat#48]
Here, shouldn't we do apt-update before ?

![image](https://user-images.githubusercontent.com/19529533/157625888-af7c5ad4-c526-4be9-938f-7f29489c87b1.png)

Available packages: 

![image](https://user-images.githubusercontent.com/19529533/157626003-7441b7a6-5010-4819-b91e-67425d68718e.png)

Error in build:

![image](https://user-images.githubusercontent.com/19529533/157626086-0e09ea80-97d2-4f46-bae2-d8bbb89ea1d6.png)

@sbidoul

**Comment by rousseldenis** [comment]
@gurneyalex

**Comment by rousseldenis** [comment]
https://runboat.odoo-community.org/webui/build.html?name=b8e2adf66-7a59-4055-b84f-6772a37ca899

**Comment by sbidoul** [comment]
Actually I think we don't need rsync anymore. 'cp -ar' should be sufficient. I'll deploy the fix tomorrow.

**Comment by sbidoul** [comment]
To OCA folks following this issue, the fix has been deployed on runboat.odoo-community.org.
Clicking reset on builds that failed due to this should be sufficient to redeploy correctly.
![image](https://user-images.githubusercontent.com/692075/158056139-280178d2-4a99-4d8e-9bcd-1672a4fd2584.png)

**Comment by sbidoul** [comment]
I'm perplexed about the root cause, though. Followup discussion in https://github.com/OCA/oca-ci/issues/26.
