### ISSUE TITLE
DevOps Workflow

### ISSUE THREAD

**Issue by JuanDCG** [sbidoul/runboat#51]
I'm looking Runboat and I'm interested in contribute.

GitHub is a fact in OCA, but k8s is "new".

I have been researching for years the Odoo/OCA ecosystem and k8s, and to sum up I suggest use [Microk8s](microk8s.io) for experiments or production.

And I also propose use [Portainer](portainer.io) for GitOps, CI/CD management... DevOps Workflow.

**Comment by sbidoul** [comment]
> I'm looking Runboat and I'm interested in contribute.

Great!

I'm not sure what you are proposing to contribute, though. Can you elaborate ?

**Comment by JuanDCG** [comment]
Yes, of course, I can advice you in k8s issues and "DevOps workflow", and contribute from my local environment with microk8s to test your development.

If you are interested in Microk8s, I'm running a demo here [micro-cloud-odoo](https://github.com/314-consulting/micro-cloud-odoo).

Then, you act as main to guidance my contributions. So, if you like, you can assign to me an issue ( and be patient because I have only a bit time ).

I miss a kanban project of Runboat/oca-ci, to understand your roadmap.

**Comment by sbidoul** [comment]
> I miss a kanban project of Runboat/oca-ci, to understand your roadmap.

There is no roadmap. There are open issues, mostly feature suggestions, for which contributions are welcome.

As there is nothing actionnable here, allow me to close this issue. Feel free to open other issues with specific topics you want to address.
